[package]
name = "smelter-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.12", features = ["blocking", "json"]}
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"
